### ISSUE TITLE
Documentation parse error

### ISSUE THREAD

**Issue by Red3Tango** [ninstar/Godot-StateMachineNodes#1]
Having any comments before the initial Documentation Comment `##` for Brief/Description will not parse. So the Copyright notice at the top of the script files prevent documentation for showing in help search `F1` or in Inspector Tooltips.

**Comment by ninstar** [comment]
Likely related to this issue which is still open: https://github.com/godotengine/godot/issues/72406

**Comment by Red3Tango** [comment]
Tested:
Removed the license blurb in state_machine.gd (outside of Godot while it was closed). The Docs show up in F1.
Opened state_node.gd (in Godot) made a change and saved. The Docs show up in F1
Reload editor and Docs for StateMachine are not there.

So sadly it does look like this is a bug with Godot. Either way I really like the approach you took with this plugin, simple yet well structured. Guess the workaround for now is to open the scripts and force a save smh.

**Comment by ninstar** [comment]
The issue should be fixed for now, I moved the add-on license to a separate file until they fix the documentation parser.
