### ISSUE TITLE
Unclear about creating StateNode

### ISSUE THREAD

**Issue by Red3Tango** [ninstar/Godot-StateMachineNodes#2]
Recommend something in the documentation that states you need to extend the script and override specific methods?

More experienced users may come to this conclusion as there are no `@export` properties or custom Signals, however, it may help less-experienced users?

**Comment by ninstar** [comment]
Originally I had a feeling that the example given in the StateNode documentation would be enough to show that the `process_` methods should be overriden.

![image](https://github.com/ninstar/Godot-StateMachineNodes/assets/17078648/96795de3-3b88-48ee-853c-89e0097fc0a3)

I can add a line explicitly stating the `process_`  , `enter`, `exit` and `state_machine_ready`  should be overridden until tagging methods as virtual is made possible.

**Comment by ninstar** [comment]
Addressed by https://github.com/ninstar/Godot-StateMachineNodes/commit/65287c3098ca28f739cfdaa5a6a1136f85710c0a
