### ISSUE TITLE
Request: Re-Add Input methods

### ISSUE THREAD

**Issue by Red3Tango** [ninstar/Godot-StateMachineNodes#3]
If this is beyond your design-scope it would be trivial for me to locally add this functionality back myself. However, I do think having the ability to utilize the `*_input()` methods inside of a state can be useful.

For my setup, I have a State Machine on my player controller that uses `_input()` to parse stuff that are state-dependent, and a State Machine for my UI that overrides stuff in `_unhandled_input()` based on the context of the UI.

**Comment by ninstar** [comment]
StateNodes have `is_current_state()` method that can be checked in situations where inputs are being handled by each StateNode independently.

I removed the methods mentioned to avoid potential unexpected behaviour as they rely on the viewport the node is on, but I can add them back in case inputs being consumed by the StateMachine itself is necessary.

**Comment by Red3Tango** [comment]
Never thought about utilizing it that way, just have `_input()` on the state and a guard statement checking `is_current_state()`. Just wasn't sure how performant that would be if there are several states that are all doing that.

Good case for "will cross that bridge when I get there". I could just disable processing on the node when its not active anymore, either way, thanks for the response and suggestion.
